language: node_js

node_js: 6.0.0

install:
  - npm install acyort -g

before_script:
  - git clone https://github.com/willhunger/BlogBuild.git public
  - cd public

script:
  - cd ../
  - acyort init
  - cp config.bak.yml config.yml
  - rm config.bak.yml
  - git clone https://github.com/acyortjs/theme-donob.git themes/donob
  - acyort build

after_script:
  - cd public
  - git add .
  - git config user.name "willhunger"
  - git config user.email "willhunger@foxmail.com"
  - git commit -m "update from travis-ci"
  - git push https://${GH_TOKEN}@github.com/willhunger/BlogBuild.git gh-pages:gh-pages
