# site
# default "AcyOrt", "A Node.js blog tool powered by GitHub."
title: Will's Blog
description: No choice is the best choice

# timezone
# the timezone of your website
# example: America/New_York, Japan, or UTC
# default is local system timezone
timezone:

# rss
# set false if no need rss output
# default "rss.xml"
rss:

# site url. you can set as 'http://yoursite.com/child' if necessary
# please add 'http://' or 'https://'
# default "https://acyortjs.github.io"
url: http://will66.me/

# language
# base on the theme support
# default "en"
language:

# theme
# default "ccc45"
theme: donob

# pagination
# set 0 if no need paging
# default 10, 30
per_page: 5
archives_per_page: 

# thumbnail mode
# 1: use the first image as thumbnail and remove the image
# 2: use the first image as thumbnail but not remove the image
# default 2ss
thumbnail_mode: 2

# menu
menu:
  Archives: /archives/
  Friends: /friends/
  About: /about/

# category
# default "uncategorized"
default_category: Blog

# html output directory or child directory e.g. 'child'
# default "/"
public_dir: public

# category directory
# default "category"
category_dir:

# tag directory
# default "tag"
tag_dir:

# post directory
# default "posts"
post_dir:

# archives directory
# default "archives"
archives_dir:

# site content source
# your github user/repository
# default "acyortjs", "acyortjs.github.io"
user: willhunger
repository: Blog

# post authors
# github username
authors:
  - willhunger
#  - author1

# gitHub access token(optional)
# token should be separated by '#' if you push this file to github
token: b#7ec6cd8ef528c7d0b2af45fb9ed60364db8a00c

# json output
# boolean or string
# you can set json output path
# default false
json: ture

# dev mode
# default false
dev:

# other
# customize some settings if necessary

disqus: willhunger
keywords: Python, Web
# favicon:
